### ISSUE TITLE
database initialization

### ISSUE THREAD

**Issue by peter9370** [JohanDhana/blog-ci4#1]
I'm starting from scratch with this, so I don't have a current database.  Do you have a file describing the structure of the database? 

(Apologies if I'm missing something.)

**Comment by JohanDhana** [comment]
I must have forgotten to add it. I will add it tomorrow.

**Comment by peter9370** [comment]
That would be great - thanks very much.

**Comment by JohanDhana** [comment]
i added the db file and migrations

**Comment by peter9370** [comment]
Many thanks for that
